#!/bin/bash

# BEGIN MEDIA INFO
ALL_APP_CAT+=':MEDIA'
APP_MEDIA_CAT="Media Application"
APP_MEDIA_EX="Media Application"
# END MEDIA INFO

APP_MEDIA_NAME[0]="VLC"
APP_MEDIA_PKG[0]="vlc"
APP_MEDIA_DESC[0]="Media Player"
APP_MEDIA_STAT[0]="ON"
