#!/bin/bash

# BEGIN WM INFO
ALL_APP_CAT+=':<CAT>'
APP_<CAT>_CAT="Categorie Name"
APP_<CAT>_EX="Categorie Description"
# end WM INFO

APP_<CAT>_NAME[0]="<Name>"
APP_<CAT>_PKG[0]="package" 
APP_<CAT>_DESC[0]="Description of the package"
APP_<CAT>_STAT[0]="OFF"
<Name>_routine () {
	ALL_REPO_ADD+=" ppa:<name>/<repo>"
    ALL_PKG_CHOOSEN+=" APP_<CAT>_PKG[0]"
    
}

